global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api01
    # scrape_interval: 2s
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [api01:3000]

  - job_name: api02
    # scrape_interval: 2s
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [api02:3000]
